# Generated by Django 4.2.11 on 2026-06-19 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CupStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=10, help_text='Alerta cuando baje de este valor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock de Vasos',
                'verbose_name_plural': 'Stock de Vasos',
            },
        ),
        migrations.CreateModel(
            name='FlavorBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('creamy', 'Bolsa Cremosos'), ('refreshing', 'Bolsa Refrescantes'), ('water', 'Bolsa Agua')], max_length=20)),
                ('stock_ml', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('min_stock_ml', models.DecimalField(decimal_places=2, default=Decimal('500'), help_text='Alerta cuando baje de este valor (ml)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bolsa de Sabor',
                'verbose_name_plural': 'Bolsas de Sabores',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('sale', 'Venta'), ('adjustment', 'Ajuste')], max_length=15)),
                ('quantity_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_units', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
