# Generated by Django 4.2.11 on 2026-06-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cup_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.cupstock'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='flavor_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.flavorbag'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='flavorbag',
            name='flavor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bag', to='products.flavor'),
        ),
        migrations.AddField(
            model_name='cupstock',
            name='cup_size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.cupsize'),
        ),
    ]
