# Generated by Django 4.2.11 on 2026-09-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promotion_category_platform_fee_promotionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
    ]
