# Generated by Django 4.2.11 on 2026-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_promotion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='topping_bags_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='topping_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
