# Generated by Django 4.2.11 on 2026-06-19 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_cash', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('expected_transfer', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('actual_cash', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('actual_transfer', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cups_16oz_system', models.IntegerField(default=0)),
                ('cups_16oz_actual', models.IntegerField(default=0)),
                ('cups_24oz_system', models.IntegerField(default=0)),
                ('cups_24oz_actual', models.IntegerField(default=0)),
                ('bags_creamy_system', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('bags_creamy_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('bags_refreshing_system', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('bags_refreshing_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
            },
        ),
    ]
