# Generated by Django 4.2.11 on 2026-09-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_sellercashdelivery_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashaudit',
            name='bags_creamy_actual',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='bags_creamy_system',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='bags_refreshing_actual',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='bags_refreshing_system',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='cups_16oz_actual',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='cups_16oz_system',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='cups_24oz_actual',
        ),
        migrations.RemoveField(
            model_name='cashaudit',
            name='cups_24oz_system',
        ),
    ]
