# Generated by Django 4.2.11 on 2026-10-01 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cash', '0010_remove_cashaudit_bags_creamy_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaudit',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashaudit',
            name='delivered_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
