# Generated by Django 4.2.11 on 2026-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CupSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('8oz', '8 oz'), ('12oz', '12 oz'), ('16oz', '16 oz'), ('24oz', '24 oz')], max_length=10, unique=True)),
                ('ml', models.DecimalField(decimal_places=2, help_text='Mililitros equivalentes', max_digits=8)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tamaño de Vaso',
                'verbose_name_plural': 'Tamaños de Vaso',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('water', 'Granizado en Agua'), ('creamy', 'Granizado Cremoso'), ('refreshing', 'Refrescante')], default='water', max_length=20)),
                ('color', models.CharField(default='#00E5FF', help_text='Color hex para UI', max_length=7)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sabor',
                'verbose_name_plural': 'Sabores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('single', 'Sabor único'), ('combo', 'Combinado'), ('bomb', 'Bomba')], default='single', max_length=10)),
                ('requires_topping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Topping',
                'verbose_name_plural': 'Toppings',
            },
        ),
    ]
