# Generated by Django 4.2.11 on 2026-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_flavor_licores'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupsize',
            name='topping_bags_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupsize',
            name='topping_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
