# Generated by Django 4.2.11 on 2026-06-19 23:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=15)),
                ('cash_received', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('transfer_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('transfer_reference', models.CharField(blank=True, max_length=100)),
                ('total', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('change_given', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('is_delivery', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cup_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.cupsize')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
        migrations.CreateModel(
            name='SaleItemFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_consumed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.flavor')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitems_flavors', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Sabor de Item',
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='flavors',
            field=models.ManyToManyField(through='sales.SaleItemFlavor', to='products.flavor'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.topping'),
        ),
    ]
