# Generated by Django 4.2.11 on 2026-09-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_seller_name_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_number',
        ),
    ]
