# Generated by Django 4.2.11 on 2026-10-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_flavor_licores'),
        ('sales', '0008_remove_sale_sale_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='auto_topping_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='auto_topping_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automatic_sale_items', to='products.topping'),
        ),
    ]
